version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: autoshop_n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=development
      - WEBHOOK_URL=https://jarred-epiphysial-psychically.ngrok-free.dev/
      - GENERIC_TIMEZONE=Africa/Tunis
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
      - mailpit

  postgres:
    image: postgres:16
    container_name: autoshop_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=autoshop_user
      - POSTGRES_PASSWORD=autoshop_password
      - POSTGRES_DB=autoshop_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: autoshop_mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

  metabase:
    image: metabase/metabase:latest
    container_name: autoshop_metabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  ngrok:
    image: ngrok/ngrok:latest
    container_name: autoshop_ngrok
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=3C1XQGe3Axor9IUp0vexRCZl3x8_83qX7J2amEM3mYjQ9UEmo
    command: http n8n:5678
    depends_on:
      - n8n

volumes:
  n8n_data:
  postgres_data: